# Generated by Django 4.1.5 on 2023-01-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
