# Generated by Django 4.1.5 on 2023-01-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_game_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='game_15px',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_2px',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_30px',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_50px',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
